In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("Purchase_data.csv")
print(df)

A = df[["Candies (#)", "Mangoes (Kg)", "Milk Packets (#)"]].values
print("MatrixA=",A)

C = df[["Payment (Rs)"]].values
print("MatrixC=",C)

Adim = A.shape
print("Dimentionality of Matrix A is",Adim)

Cdim = C.shape
print("Dimentionality of Matrix C is",Cdim)

nA= A.shape[0]
print("Number of vectors in Matrix A is",nA)

nC= C.shape[0]
print("Number of vectors in Matrix A is",nC)

print("The Rank of Matrix A is ", np.linalg.matrix_rank(A))

A_inverse= np.linalg.pinv(A)
print("The Pseudo-inverse of Matrix A is ", A_inverse)

X = np.dot(A_inverse,C)
print(X)

df['RICH/POOR'] = df['Payment (Rs)'].apply(lambda x: 'RICH' if x > 200 else 'POOR')
print(df.to_string())


  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198
MatrixA= [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
MatrixC= [[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]
Dimentionality of Ma